-- 통합 재고 관리 테이블 (일자별 snapshot)
CREATE TABLE IF NOT EXISTS integrated_inventory (
  id             INT UNSIGNED NOT NULL AUTO_INCREMENT,
  snapshot_date  DATE         NOT NULL COMMENT '스냅샷 일자',
  vehicle        VARCHAR(100) DEFAULT NULL COMMENT '차종',
  part           VARCHAR(100) DEFAULT NULL COMMENT '부위',
  color          VARCHAR(100) DEFAULT NULL COMMENT '칼라',
  product_code   VARCHAR(100) DEFAULT NULL COMMENT '완제품 코드',
  supplier       VARCHAR(100) DEFAULT NULL COMMENT '업체',
  two_width      DECIMAL(10,3) DEFAULT NULL COMMENT '두폭',
  thickness      DECIMAL(10,3) DEFAULT NULL COMMENT '두께',
  ratio          DECIMAL(10,3) DEFAULT NULL COMMENT '배율',
  width          DECIMAL(10,2) DEFAULT NULL COMMENT '폭',
  length         DECIMAL(10,2) DEFAULT NULL COMMENT '길이',
  gyeongju_top   DECIMAL(14,3) DEFAULT NULL COMMENT '경주상지(M)',
  gyeongju_cover DECIMAL(14,3) DEFAULT NULL COMMENT '경주표지(M)',
  ulsan_cover    DECIMAL(14,3) DEFAULT NULL COMMENT '울산표지(M)',
  bottom_qty     DECIMAL(14,3) DEFAULT NULL COMMENT '하지(M)',
  foam_total     DECIMAL(14,3) DEFAULT NULL COMMENT '폼 총수량(M)',
  foam_raw       DECIMAL(14,3) DEFAULT NULL COMMENT '미처리 폼(M)',
  primer_qty     DECIMAL(14,3) DEFAULT NULL COMMENT '프라이머(M)',
  finished_qty   DECIMAL(14,3) DEFAULT NULL COMMENT '완제품(EA)',
  row_order      INT          DEFAULT 0 COMMENT '엑셀 상의 행 순서',
  upload_batch   VARCHAR(40)  DEFAULT NULL COMMENT '업로드 배치 ID',
  uploaded_by    VARCHAR(100) DEFAULT NULL,
  uploaded_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_snapshot    (snapshot_date),
  INDEX idx_vehicle     (vehicle),
  INDEX idx_product     (product_code),
  INDEX idx_upload      (upload_batch)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
