-- 엠보 생산 실적 테이블
CREATE TABLE IF NOT EXISTS production_emboss (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  prod_date     DATE         NOT NULL,
  machine_no    VARCHAR(50)  DEFAULT NULL COMMENT '호기',
  bnk_lot       VARCHAR(100) DEFAULT NULL COMMENT 'BnK LOT',
  top_lot       VARCHAR(100) DEFAULT NULL COMMENT '상지LOT',
  cover_lot     VARCHAR(100) DEFAULT NULL COMMENT '표지LOT',
  vehicle       VARCHAR(100) DEFAULT NULL COMMENT '차종',
  color         VARCHAR(100) DEFAULT NULL COMMENT '칼라',
  part          VARCHAR(100) DEFAULT NULL COMMENT '부위',
  spec          VARCHAR(200) DEFAULT NULL COMMENT '규격',
  sheet_qty     INT          DEFAULT NULL COMMENT '시트수량',
  foam_lot      VARCHAR(100) DEFAULT NULL COMMENT 'FOAM LOT',
  foam_in_qty   INT          DEFAULT NULL COMMENT 'FOAM 입고수량',
  emboss_roll   VARCHAR(100) DEFAULT NULL COMMENT '엠보롤',
  width         VARCHAR(50)  DEFAULT NULL COMMENT '폭(두폭)',
  emboss_qty    INT          DEFAULT NULL COMMENT '엠보생산량',
  yield_rate    DECIMAL(10,6) DEFAULT NULL COMMENT '수율',
  gloss         VARCHAR(100) DEFAULT NULL COMMENT '광택',
  thickness     DECIMAL(8,3) DEFAULT NULL COMMENT '두께',
  double_width  VARCHAR(50)  DEFAULT NULL COMMENT '2폭여부',
  total_qty     INT          DEFAULT NULL COMMENT '총생산량',
  roll_qty      INT          DEFAULT NULL COMMENT '롤',
  count_qty     INT          DEFAULT NULL COMMENT '수량',
  actual_usage  INT          DEFAULT NULL COMMENT '실사용량',
  memo          VARCHAR(500) DEFAULT NULL,
  deleted       CHAR(1)      NOT NULL DEFAULT 'N',
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by    VARCHAR(100) DEFAULT NULL,
  updated_by    VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX idx_prod_date (prod_date),
  INDEX idx_vehicle   (vehicle),
  INDEX idx_color     (color),
  INDEX idx_deleted   (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
