-- 재단 생산 실적 테이블
CREATE TABLE IF NOT EXISTS production_cutting (
  id                 INT UNSIGNED NOT NULL AUTO_INCREMENT,
  prod_date          DATE         NOT NULL COMMENT '재단일자',
  machine_no         VARCHAR(50)  DEFAULT NULL COMMENT '설비',
  cut_lot            VARCHAR(100) DEFAULT NULL COMMENT '재단LOT',
  bnk_lot            VARCHAR(100) DEFAULT NULL COMMENT 'BnK LOT',
  sheet_lot          VARCHAR(100) DEFAULT NULL COMMENT '시트LOT',
  cover_lot          VARCHAR(100) DEFAULT NULL COMMENT '표지LOT',
  foam_lot           VARCHAR(100) DEFAULT NULL COMMENT '폼LOT',
  foam_back_lot      VARCHAR(100) DEFAULT NULL COMMENT '폼이면처리LOT',
  vehicle            VARCHAR(100) DEFAULT NULL COMMENT '차종',
  part               VARCHAR(100) DEFAULT NULL COMMENT '부위',
  color              VARCHAR(100) DEFAULT NULL COMMENT '색상',
  emboss             VARCHAR(100) DEFAULT NULL COMMENT '엠보',
  spec               VARCHAR(200) DEFAULT NULL COMMENT '양산규격',
  width_check        DECIMAL(10,2) DEFAULT NULL COMMENT '폭 확인',
  length_check       DECIMAL(10,2) DEFAULT NULL COMMENT '길이 확인',
  single_double      INT          DEFAULT NULL COMMENT '단폭/두폭 (1/2)',
  label_qty          INT          DEFAULT NULL COMMENT '라벨(ea)',
  real_qty           INT          DEFAULT NULL COMMENT '실갯수(ea)',
  in_qty             DECIMAL(10,2) DEFAULT NULL COMMENT '입고(m)',
  input_remain       DECIMAL(10,2) DEFAULT NULL COMMENT '투입잔량',
  cut_qty            INT          DEFAULT NULL COMMENT '재단(ea)',
  remain_qty         DECIMAL(10,2) DEFAULT NULL COMMENT '남은잔량',
  cal_pigment        INT          DEFAULT NULL COMMENT 'CAL 안료',
  cal_line           INT          DEFAULT NULL COMMENT 'CAL 경선',
  cal_other          INT          DEFAULT NULL COMMENT 'CAL 기타',
  foam_defect        INT          DEFAULT NULL COMMENT '폼 불량',
  top_knife_mark     INT          DEFAULT NULL COMMENT '표지 칼줄',
  top_flow_mark      INT          DEFAULT NULL COMMENT '표지 흐름자국',
  emb_width_minor    INT          DEFAULT NULL COMMENT '엠보 폭(미미)',
  emb_roll_mark      INT          DEFAULT NULL COMMENT '엠보 롤자국',
  emb_oil_mark       INT          DEFAULT NULL COMMENT '엠보 오일자국',
  emb_contamination  INT          DEFAULT NULL COMMENT '엠보 오염',
  emb_wrinkle        INT          DEFAULT NULL COMMENT '엠보 구김',
  emb_chew           INT          DEFAULT NULL COMMENT '엠보 씹힘',
  emb_wind           INT          DEFAULT NULL COMMENT '엠보 바람',
  emb_connect        INT          DEFAULT NULL COMMENT '엠보 연결',
  cut_foreign        INT          DEFAULT NULL COMMENT '재단/합판 이물',
  cut_length_defect  INT          DEFAULT NULL COMMENT '재단/합판 길이불량',
  defect_subtotal    INT          DEFAULT NULL COMMENT '최종불량 소계(ea)',
  missing_qty        DECIMAL(12,3) DEFAULT NULL COMMENT '누락수량(ea)',
  final_defect_m     DECIMAL(12,3) DEFAULT NULL COMMENT '최종불량수량(m)',
  memo               VARCHAR(500) DEFAULT NULL COMMENT '비고',
  deleted            CHAR(1)      NOT NULL DEFAULT 'N',
  created_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by         VARCHAR(100) DEFAULT NULL,
  updated_by         VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX idx_prod_date (prod_date),
  INDEX idx_vehicle   (vehicle),
  INDEX idx_color     (color),
  INDEX idx_deleted   (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
